webtalk_init -webtalk_dir D:/xilinx_prj/xilinx_axi/zcu104/vdma.sim/sim_1/behav/xsim/xsim.dir/sim_video_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 18 22:03:15 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f53355a6-2385-4b47-940c-2b0307f7c4fd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5d49eded299a42a0a257090021fd44c9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3418 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2129980 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "6" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.75_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "25680_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2080271495 -regid "" -xml D:/xilinx_prj/xilinx_axi/zcu104/vdma.sim/sim_1/behav/xsim/xsim.dir/sim_video_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/xilinx_prj/xilinx_axi/zcu104/vdma.sim/sim_1/behav/xsim/xsim.dir/sim_video_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/xilinx_prj/xilinx_axi/zcu104/vdma.sim/sim_1/behav/xsim/xsim.dir/sim_video_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
