# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/axi_vd/axi_vd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_vd || ORIG_REF_NAME==axi_vd} -quiet] -quiet

# IP: bd/axi_vd/ip/axi_vd_smartconnect_0_0/axi_vd_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_vd_smartconnect_0_0 || ORIG_REF_NAME==axi_vd_smartconnect_0_0} -quiet] -quiet

# IP: bd/axi_vd/ip/axi_vd_proc_sys_reset_0_0/axi_vd_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_vd_proc_sys_reset_0_0 || ORIG_REF_NAME==axi_vd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/axi_vd/ip/axi_vd_xlconstant_0_0/axi_vd_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_vd_xlconstant_0_0 || ORIG_REF_NAME==axi_vd_xlconstant_0_0} -quiet] -quiet

# IP: bd/axi_vd/ip/axi_vd_axi_read_1_0/axi_vd_axi_read_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_vd_axi_read_1_0 || ORIG_REF_NAME==axi_vd_axi_read_1_0} -quiet] -quiet

# IP: bd/axi_vd/ip/axi_vd_axi_write_0_1/axi_vd_axi_write_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_vd_axi_write_0_1 || ORIG_REF_NAME==axi_vd_axi_write_0_1} -quiet] -quiet

# IP: bd/axi_vd/ip/axi_vd_s_axi_mm_0_1/axi_vd_s_axi_mm_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_vd_s_axi_mm_0_1 || ORIG_REF_NAME==axi_vd_s_axi_mm_0_1} -quiet] -quiet

# IP: bd/axi_vd/ip/axi_vd_system_ila_0_3/axi_vd_system_ila_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_vd_system_ila_0_3 || ORIG_REF_NAME==axi_vd_system_ila_0_3} -quiet] -quiet

# XDC: bd/axi_vd/axi_vd_ooc.xdc
