# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_param synth.incrementalSynthesisCache C:/Users/zhi/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-4204-weslie/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/xilinx_axi/tp/zcu104/vdma.cache/wt [current_project]
set_property parent.project_path E:/xilinx_axi/tp/zcu104/vdma.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu104:part0:1.1 [current_project]
set_property ip_repo_paths {
  e:/xilinx_axi/tp/ip_repo/s_axi_mm_1.0
  e:/xilinx_axi/tp/ip_repo/axi_rd/ip
  e:/xilinx_axi/tp/ip_repo/axi_wr/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo e:/xilinx_axi/tp/zcu104/vdma.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/new/Video_DMA.v
add_files E:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/axi_vd.bd
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_1/bd_17d7_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_1/bd_17d7_psr0_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_2/bd_17d7_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_2/bd_17d7_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_3/bd_17d7_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_3/bd_17d7_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_4/bd_17d7_psr_aclk2_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_4/bd_17d7_psr_aclk2_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_5/bd_17d7_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_6/bd_17d7_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_7/bd_17d7_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_8/bd_17d7_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_9/bd_17d7_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_13/bd_17d7_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_14/bd_17d7_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_15/bd_17d7_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_16/bd_17d7_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_20/bd_17d7_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_21/bd_17d7_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_22/bd_17d7_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_23/bd_17d7_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_24/bd_17d7_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_25/bd_17d7_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_26/bd_17d7_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_27/bd_17d7_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_smartconnect_0_0/bd_0/ip/ip_28/bd_17d7_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_proc_sys_reset_0_0/axi_vd_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_proc_sys_reset_0_0/axi_vd_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_proc_sys_reset_0_0/axi_vd_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_system_ila_0_3/bd_0/ip/ip_0/bd_e3e9_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_system_ila_0_3/bd_0/bd_e3e9_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/ip/axi_vd_system_ila_0_3/axi_vd_system_ila_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/bd/axi_vd/axi_vd_ooc.xdc]

read_ip -quiet E:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/ip/clk_wiz/clk_wiz.xci
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/ip/clk_wiz/clk_wiz_board.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/ip/clk_wiz/clk_wiz.xdc]
set_property used_in_implementation false [get_files -all e:/xilinx_axi/tp/zcu104/vdma.srcs/sources_1/ip/clk_wiz/clk_wiz_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Video_DMA -part xczu7ev-ffvc1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Video_DMA.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Video_DMA_utilization_synth.rpt -pb Video_DMA_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
