# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xilinx_prj/xilinx_axi/Video_dma/prj/video_dma.srcs/sources_1/ip/axis_fifo_in/axis_fifo_in.xci
# IP: The module: 'axis_fifo_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx_prj/xilinx_axi/Video_dma/prj/video_dma.srcs/sources_1/ip/axis_fifo_in/axis_fifo_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_fifo_in'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_axi/Video_dma/prj/video_dma.srcs/sources_1/ip/axis_fifo_in/axis_fifo_in.xci
# IP: The module: 'axis_fifo_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx_prj/xilinx_axi/Video_dma/prj/video_dma.srcs/sources_1/ip/axis_fifo_in/axis_fifo_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_fifo_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
